{
  "agent_build": "6.8.2.112-09AFB",
  "group_name": watchmanGroupName,
  "plugins": [{
    "status": prStatusFalseMounts,
    "name": "False Mounts",
    "uuid": "6253d5a9-2d8f-4ca8-b9d0-1fe8d4217ab1",
    "summary": prDetailsFalseMounts,
    "version": "6.8.2.112-09AFB",
    "run_time": 1,
    "slug": "false-mounts",
    "metadata": []
  }, {
    "status": prStatusRootCapacity,
    "name": "Root Capacity",
    "uuid": "724358f6-ab88-43df-afcb-3a22bb2b72ef",
    "summary": prDetailsRootCapacity,
    "version": "6.8.2.112-09AFB",
    "run_time": 1,
    "slug": "root-capacity",
    "metadata": [{
      "name": driveName,
      "datatype": "string",
      "include_in_warning": false,
      "value": [{
        "name": "Purgeable Space",
        "datatype": "string",
        "include_in_warning": false,
        "value": drivePurgeableSpace,
        "visible": true,
        "identifier": "purgeable_space"
      }, {
        "name": "Format",
        "datatype": "string",
        "include_in_warning": false,
        "value": driveFormat,
        "visible": true,
        "identifier": "format"
      }, {
        "name": "Free Space",
        "datatype": "string",
        "include_in_warning": false,
        "value": driveFreeSpace,
        "visible": true,
        "identifier": "free_space"
      }, {
        "name": "Percent Full",
        "datatype": "string",
        "include_in_warning": false,
        "value": drivePercentFull,
        "visible": true,
        "identifier": "percent_full"
      }, {
        "name": "Total Size",
        "datatype": "string",
        "include_in_warning": false,
        "value": driveCapacity,
        "visible": true,
        "identifier": "total_size"
      }],
      "visible": true,
      "identifier": "root-disk"
    }]
  }, {
    "status": prStatusLaptopBattery,
    "name": "Laptop Battery",
    "uuid": "ccce52db-63b3-4748-b6b0-2ed2b566ab87",
    "summary": prDetailsLaptopBattery,
    "version": "6.8.2.112-09AFB",
    "run_time": 1,
    "slug": "laptop-battery",
    "metadata": []
  }, {
    "status": prStatusPost ,
    "name": "POST",
    "uuid": "53a1a71c-5ec1-4a32-921a-af00852e279a",
    "summary": prDetailsPost,
    "version": "6.8.2.112-09AFB",
    "run_time": 1,
    "slug": "post",
    "metadata": []
  }, {
    "status": prStatusMonitoringAgent,
    "name": "Monitoring Agent",
    "uuid": "2eeb24fa-5a41-453f-885f-197bab9db1ce",
    "summary": prDetailsMonitoringAgent,
    "version": "6.8.2.112-09AFB",
    "run_time": 1,
    "slug": "monitoring-agent",
    "metadata": []
  }, {
    "status": prStatusDriveErrors,
    "name": "Disk IO Errors",
    "uuid": "efe964b5-a390-4d06-a66d-696f538eaa56",
    "summary": prDetailsDriveErrors,
    "version": "6.8.2.112-09AFB",
    "run_time": 10,
    "slug": "disk-io-errors",
    "metadata": []
  }, {
    "status": prStatusMalware,
    "name": "Malware",
    "uuid": "1b103d63-5ac0-4ae7-a880-480eb5122037",
    "summary": prDetailsMalware,
    "version": "6.8.2.112-09AFB",
    "run_time": 1,
    "slug": "malware",
    "metadata": []
  }, {
    "status": prStatusS1,
    "name": "SentinelOne",
    "uuid": "6B006534-1EA5-49F9-A9E0-77643D7B89D2",
    "summary": prDetailsS1,
    "version": "1.2.0.1",
    "run_time": 1,
    "slug": "sentinelone",
    "metadata": []
  }, {
    "status": prStatusMdm,
    "name": "MDM",
    "uuid": "d83494df-9406-4ade-a791-23b1c1fda07c",
    "summary": prDetailsMdm,
    "version": "1.1.0.1",
    "run_time": 1,
    "slug": "mdm",
    "metadata": []
  }, {
    "status": prStatusIpAddress,
    "name": "Local IP Address",
    "uuid": "997cc881-ab77-4572-8aa7-b4acfbf453cf",
    "summary": prDetailsIpAddress,
    "version": "6.8.2.112-09AFB",
    "run_time": 1,
    "slug": "local-ip-address",
    "metadata": []
  }, {
    "status": prStatusMacosUpdates,
    "name": "macOS Updates",
    "uuid": "E475A6BC-39F5-4CF9-8A63-B9A241734092",
    "summary": prDetailsMacosUpdates,
    "version": "1.5.0.0",
    "run_time": 141,
    "slug": "macos-updates",
    "metadata": []
  }, {
    "status": prStatusWindowsUpdate,
    "name": "Windows Update",
    "uuid": "E475A6BC-39F5-4CF9-8A63-B9A241734092",
    "summary": prDetailsWindowsUpdate,
    "version": "1.5.0.0",
    "run_time": 141,
    "slug": "windows-update",
    "metadata": []
  }, {
    "status": prStatusLinuxUpdates,
    "name": "Linux Updates",
    "uuid": "7DDF5856-A27F-49B7-B831-AEFC5612C4DC",
    "summary": prDetailsLinuxUpdates,
    "version": "1.5.0.0",
    "run_time": 141,
    "slug": "linux-updates",
    "metadata": []
  }, {
    "status": prStatusActivationLock,
    "name": "Activation Lock",
    "uuid": "E2E1633E-B763-4EA0-8F68-49334FF75E51",
    "summary": prDetailsActivationLock,
    "version": "1.2.0.0",
    "run_time": 1,
    "slug": "activation-lock",
    "metadata": []
  }, {
    "status": prStatusUserAccounts,
    "name": "User Accounts",
    "uuid": "3DDE4C8D-8078-44A6-9E26-C66FEDB12371",
    "summary": prDetailsUserAccounts,
    "version": "1.0.1.0",
    "run_time": 1,
    "slug": "user-accounts",
    "metadata": []
  }, {
    "status": prStatusUmbrella,
    "name": "Umbrella DNS",
    "uuid": "04B5C694-B132-43AA-8106-799C4D9F99B3",
    "summary": prDetailsUmbrella,
    "version": "1.3.0.1",
    "run_time": 1,
    "slug": "umbrella-dns",
    "metadata": []
  }, {
    "status": prStatusRam,
    "name": "RAM",
    "uuid": "41301e2d-e7bf-4be1-bd87-00609ddac3c3",
    "summary": prDetailsRam,
    "version": "6.8.2.112-09AFB",
    "run_time": 1,
    "slug": "ram",
    "metadata": [{
      "name": "BANK 0/ChannelA-DIMM0",
      "parent": "",
      "visible": true,
      "datatype": "array",
      "value": [{
        "name": "name",
        "include_in_warnings": false,
        "datatype": "string",
        "value": "Physical Memory",
        "visible": true,
        "identifier": "name"
      }, {
        "name": "manufacturer",
        "include_in_warnings": false,
        "datatype": "string",
        "value": ram0Manufacturer,
        "visible": true,
        "identifier": "manufacturer"
      }, {
        "name": "capacity",
        "include_in_warnings": false,
        "datatype": "string",
        "value": ram0Capacity,
        "visible": true,
        "identifier": "capacity"
      }, {
        "name": "type",
        "include_in_warnings": false,
        "datatype": "string",
        "value": ram0Type,
        "visible": true,
        "identifier": "type"
      }, {
        "name": "speed",
        "include_in_warnings": false,
        "datatype": "string",
        "value": ram0Speed,
        "visible": true,
        "identifier": "speed"
      }, {
        "name": "status",
        "include_in_warnings": false,
        "datatype": "string",
        "value": "ok",
        "visible": true,
        "identifier": "status"
      }],
      "include_in_warnings": false,
      "identifier": "BANK 0/ChannelA-DIMM0"
    }, {
      "name": "BANK 2/ChannelB-DIMM0",
      "parent": "",
      "visible": true,
      "datatype": "array",
      "value": [{
        "name": "name",
        "include_in_warnings": false,
        "datatype": "string",
        "value": "Physical Memory",
        "visible": true,
        "identifier": "name"
      }, {
        "name": "manufacturer",
        "include_in_warnings": false,
        "datatype": "string",
        "value": ram1Manufacturer,
        "visible": true,
        "identifier": "manufacturer"
      }, {
        "name": "capacity",
        "include_in_warnings": false,
        "datatype": "string",
        "value": ram1Capacity,
        "visible": true,
        "identifier": "capacity"
      }, {
        "name": "type",
        "include_in_warnings": false,
        "datatype": "string",
        "value": ram1Type,
        "visible": true,
        "identifier": "type"
      }, {
        "name": "speed",
        "include_in_warnings": false,
        "datatype": "string",
        "value": ram1Speed,
        "visible": true,
        "identifier": "speed"
      }, {
        "name": "status",
        "include_in_warnings": false,
        "datatype": "string",
        "value": "ok",
        "visible": true,
        "identifier": "status"
      }],
      "include_in_warnings": false,
      "identifier": "BANK 2/ChannelB-DIMM0"
    }]
  }, {
    "status": prStatusFilevault,
    "name": "FileVault",
    "uuid": "a4e0f6c9-e2b8-4425-b9f5-0fc7e54753d0",
    "summary": prDetailsFilefault,
    "version": "6.8.2.112-09AFB",
    "run_time": 1,
    "slug": "filevault",
    "metadata": [{
      "name": "FileVault Enabled",
      "parent": "",
      "visible": false,
      "datatype": "boolean",
      "value": filevaultEnabled,
      "include_in_warnings": false,
      "identifier": "filevault_enabled"
    }]
  }, {
    "status": prStatusSmart,
    "name": "SMART",
    "uuid": "afd11499-8721-4569-8ce7-d74c14a8976b",
    "summary": prDetailsSmart,
    "version": "6.8.2.112-09AFB",
    "run_time": 1,
    "slug": "smart",
    "metadata": [{
      "name": driveName,
      "parent": "",
      "visible": true,
      "datatype": "array",
      "value": [{
        "name": "serial",
        "include_in_warnings": false,
        "datatype": "string",
        "value": driveSerialNumber,
        "visible": true,
        "identifier": "serial"
      }, {
        "name": "disk_id",
        "include_in_warnings": false,
        "datatype": "string",
        "value": "disk0",
        "visible": true,
        "identifier": "disk_id"
      }, {
        "name": "state",
        "include_in_warnings": false,
        "datatype": "string",
        "value": "Verified",
        "visible": true,
        "identifier": "state"
      }],
      "include_in_warnings": false,
      "identifier": driveName
    }]
  }, {
    "status": prStatusOs,
    "name": "Operating System",
    "uuid": "e9f72425-6e07-4ed4-8a12-91f3158a5310",
    "summary": prDetailsOs,
    "version": "6.8.2.112-09AFB",
    "run_time": 1,
    "slug": "operating-system",
    "metadata": [{
      "name": "Potential OS",
      "parent": "",
      "visible": false,
      "datatype": "string",
      "value": osAvailableUpdate,
      "include_in_warnings": false,
      "identifier": "potential_os"
    }]
  }, {
    "status": prStatusDrives,
    "name": "Volumes",
    "uuid": "18bdcdcd-cf68-4bc9-9d4d-f842ad9e4076",
    "summary": prDetailsDrives,
    "version": "6.8.2.112-09AFB",
    "run_time": 1,
    "slug": "volumes",
    "metadata": []
  }],
  "old_watchman_id": "",
  "subscriber_subdomain": watchmanDomain,
  "settings": {
    "agent_removed": "no",
    "check_settings": true,
    "updates_enabled": true
  },
  "reported_at": reportTimestamp,
  "watchman_id": watchmanDeviceId,
  "platform": watchmanOsType,
  "attributes": {
    "kernel": "21.2.0",
    "computer_name": deviceName,
    "boot_volume_capacity": driveCapacity,
    "ram": ${ramCapacity},
    "processor_cores": processorCores,
    "current_uptime": currentUptime,
    "processor_quantity": 1,
    "last_user": username,
    "processor_name": processorName,
    "active_mac_address": activeMacAddress,
    "system_mac_address": macAddress,
    "reported_tz": timezone,
    "model_number": modelNumber,
    "os_version": osVersion,
    "serial_number": serialNumber,
    "boot_rom_version": romVersion,
    "primary_ip": primaryIp,
    "last_boot": lastBootTimestamp,
    "os_version_number": osVersionNumber,
    "processor_speed": processorSpeed,
    "os_version_build": osBuildVersion,
    "leave_tmp": false,
    "product_description": deviceDescription,
    "gmt_offset": timezoneOffset,
    "boot_volume_usage": bootVolumeUsage
  },
  "payload_uuid": payloadUuid,
  "agent_version": "6.8.2.112"
}